{
 "title": "Compare performance",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "${VAR_BASE}" },
   { "name": "path", "label": "desktop", "query": "${VAR_PATH}" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Compare performance between sites\nThis is an example dashboard on how you can do to compare performance between sites. To make this dashboard work for you, you need to reconfigure the constants (template) $base and $path. "
  },
  {
   "title": "SpeedIndex",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.*.*.chrome.cable.browsertime.statistics.visualMetrics.SpeedIndex.median, 3, 4)"
    }
   ]
  },
  {
   "title": "FirstVisualChange",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.*.*.chrome.cable.browsertime.statistics.visualMetrics.FirstVisualChange.median, 3, 4)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.*.*.chrome.cable.pagexray.requests, 3, 4)"
    }
   ]
  },
  {
   "title": "Total transfer size",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.*.*.chrome.cable.pagexray.transferSize, 3, 4)"
    }
   ]
  }
 ]
}