{
 "title": "Webpagetest Page deviation",
 "tags": [ "page" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "${VAR_BASE}" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "query": "$base.$path.pageSummary.*" },
   {
    "name": "page",
    "query": "$base.$path.pageSummary.$group.*"
   },
   {
    "name": "browser",
    "query": "$base.$path.pageSummary.$domain.$page.*"
   },
   {
    "name": "location",
    "query": "$base.$path.pageSummary.$group.$page.webpagetest.*"
   },
   {
    "name": "connectivity",
    "query": "$base.$path.pageSummary.$group.$page.webpagetest.$location.*"
   },
   {
    "name": "view",
    "query": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.*"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Visual Metrics",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.render, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view, 12)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.visualComplete95, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.lastVisualChange, 11)"
    }
   ]
  },
  {
   "title": "Interactive",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.TimeToInteractive, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.FirstInteractive, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.LastInteractive, 11)"
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.SpeedIndex, 11)"
    }
   ]
  },
  {
   "title": "Timing metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.fullyLoaded, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.loadTime, 11)"
    },
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.standardDeviation.$view.TTFB, 11)"
    }
   ]
  }
 ]
}