{
 "title": "WebPagetest Page summary",
 "tags": [ "page" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "${VAR_BASE}" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "query": "$base.$path.pageSummary.*" },
   {
    "name": "page",
    "query": "$base.$path.pageSummary.$group.*"
   },
   {
    "name": "location",
    "query": "$base.$path.pageSummary.$group.$page.webpagetest.*"
   },
   {
    "name": "connectivity",
    "query": "$base.$path.pageSummary.$group.$page.webpagetest.$location.*"
   },
   {
    "name": "view",
    "query": "$base.$path.pageSummary.$group.$page.webpagetest.$location.*.data.median.*"
   }
  ]
 },
 "panels": [
  { "title": "Visual metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Render",
   "type": "singlestat",
   "description": "The Start Render is when something for the first time is painted within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.render"
    }
   ]
  },
  {
   "title": "SpeedIndex",
   "type": "singlestat",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan and you can checkout the full documentation [here](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex"
    }
   ]
  },
  {
   "title": "Visual Complete 85%",
   "type": "singlestat",
   "description": "The visual complete 85% is when 85% (or more) are finished within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85"
    }
   ]
  },
  {
   "title": "Visual Complete 95%",
   "type": "singlestat",
   "description": "The visual complete 95% is when 95% (or more) are finished within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete95"
    }
   ]
  },
  {
   "title": "Visual Complete 99%",
   "type": "singlestat",
   "description": "The visual complete 99% is when 99% (or more) are finished within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete99"
    }
   ]
  },
  {
   "title": "Last Visual Change",
   "type": "singlestat",
   "description": "The last visual change is when something for the last time is changing within the current viewport. It is calculated by analyzing a video recording of the screen.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange"
    }
   ]
  },
  { "title": "Visual metrics trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Avg last 24 hours",
   "type": "table",
   "description": "The moving average of the last 24 hours median values for the visual metrics.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), 11)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), 11)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), 11)"
    },
    {
     "target": "aliasByNode(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), 11)"
    }
   ]
  },
  {
   "title": "Relative to yesterday",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to one day back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), #E), #E), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), '1d')), #E), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), #A), #A), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), '1d')), #A), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), #C), #C), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), '1d')), #C), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), #G), #G), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), '1d')), #G), 11)"
    }
   ]
  },
  {
   "title": "Relative to last week",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to seven days back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), #E), #E), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), '7d')), #E), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), #A), #A), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), '7d')), #A), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), #C), #C), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), '7d')), #C), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), #G), #G), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), '7d')), #G), 11)"
    }
   ]
  },
  {
   "title": "Relative to last month",
   "type": "table",
   "description": "Last 24 hours averages of median metrics compared to one month back in time. \n\nRed color background means a regression, green a positive change and yellow that the change is within the margin of error. You probably need to finetune the thresholds depending of how flakey your site is. Default threshold is +-10%.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), #E), #E), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h'), '30d')), #E), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), #A), #A), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, '24h'), '30d')), #A), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), #C), #C), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h'), '30d')), #C), 11)"
    },
    {
     "target": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), #G), #G), 11)",
     "targetFull": "aliasByNode(asPercent(diffSeries(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), timeShift(movingAverage($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h'), '30d')), #G), 11)"
    }
   ]
  },
  { "title": "Technical metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fully loaded",
   "type": "singlestat",
   "description": "Fully loaded time when the last of all assets is downloaded on the page. It is calculated using the Resource Timing API where we use the last downloaded asset.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.requestsFull"
    }
   ]
  },
  {
   "title": "Total transfer size",
   "type": "singlestat",
   "description": "The total transfer size over the wire (compressed size if your asset is compressed) of all assets on the page.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.bytesIn"
    }
   ]
  },
  {
   "title": "Document ready",
   "type": "singlestat",
   "description": "domContentLoadedEventEnd : most of the time, your javascript waits for this event so you could consider that everything JS-dependant is available at this stage",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domContentLoadedEventEnd"
    }
   ]
  },
  { "title": "WebPageTest scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cache Static Content Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.score_cache"
    }
   ]
  },
  {
   "title": "CSS/JS minification score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.score_minify"
    }
   ]
  },
  {
   "title": "CSS/JS concatenation",
   "type": "singlestat",
   "description": "This score might not be meaningful if your server is on HTTP/2",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.score_combine"
    }
   ]
  },
  {
   "title": "Compression score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.score_gzip"
    }
   ]
  },
  { "title": "History of visual metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "History Start Render",
   "type": "graph",
   "description": "The history of Start Render (when something for the first time is painted within the current viewport) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.render, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.render, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.render, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  {
   "title": "History Speed Index",
   "type": "graph",
   "description": "The history of [Speed Index](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/metrics/speed-index) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  {
   "title": "History Visual Complete 85%",
   "type": "graph",
   "description": "The history of Visual Complete 85% (when 85% (or more) if the page in the current viewport is rendered) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  { "title": "History of technical metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "History Fully Loaded",
   "type": "graph",
   "description": "The history of Fully Loaded (when the last of all assets is downloaded on the page) showing the current median value, the average median per day and the average median per week.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.fullyLoaded, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  {
   "title": "History Document Ready",
   "type": "graph",
   "description": "The history of DOMContentLoadedEnd",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domContentLoadedEventEnd, 11)"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domContentLoadedEventEnd.select metric, '24h', 'avg', true), 'Daily')"
    },
    {
     "target": "alias(summarize($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domContentLoadedEventEnd, '7d', 'avg', true), 'Weekly')"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Size",
   "type": "graph",
   "description": "The total transfer size by content type.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.*.bytes, 12)"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "The total number of requests by content type.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.*.requests, 12)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "domContentLoadedEventEnd Time",
   "type": "graph",
   "description": "The time the browser takes to parse the document and execute deferred and parser-inserted scripts including the network time from the users location to your server.  It is collected using the Navigation Timing API by taking the domContentLoadedEventStart minus navigationStart.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domContentLoadedEventEnd, 'now')"
    },
    {
     "target": "alias(timeShift($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domContentLoadedEventEnd, '7d'), 'One week back')"
    },
    {
     "target": "alias(summarize(#A, '1day', 'avg', true), \"daily avg\")",
     "targetFull": "alias(summarize(alias($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.domContentLoadedEventEnd, 'now'), '1day', 'avg', true), \"daily avg\")"
    }
   ]
  },
  {
   "title": "Front End Time",
   "type": "graph",
   "description": "The time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.loadEventStart, 'now')"
    },
    {
     "target": "alias(timeShift($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.loadEventStart, '7d'), 'One week back')"
    },
    {
     "target": "alias(summarize(#A, '1day', 'avg', true), \"daily avg\")",
     "targetFull": "alias(summarize(alias($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.loadEventStart, 'now'), '1day', 'avg', true), \"daily avg\")"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "User timings",
   "type": "graph",
   "description": "All User Timing marks created on the page using the [User Timing API](https://www.w3.org/TR/user-timing/).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.userTimes.*, 12)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Chrome User Timings",
   "type": "graph",
   "description": "If WPT has been run with chrome and the --timeline option, show the [Navigation Timing API](https://www.w3.org/TR/navigation-timing/) metrics in chromeUserTiming.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.chromeUserTiming.*, 12)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Total transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 88 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.bytesIn"
    }
   ]
  },
  {
   "title": "Total CSS transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all stylesheet assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 88 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.css.bytes"
    }
   ]
  },
  {
   "title": "Total JS transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all Javascript assets served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 88 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.js.bytes"
    }
   ]
  },
  {
   "title": "Total HTML transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all HTML served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 88 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.html.bytes"
    }
   ]
  },
  {
   "title": "Total font transfer size",
   "type": "singlestat",
   "description": "The total size over the wire for all font(s) served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 88 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.font.bytes"
    }
   ]
  },
  {
   "title": "Total image size",
   "type": "singlestat",
   "description": "The total size for images served for this page.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 88 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "$base.$path.pageSummary.$group.$page.webpagetest.$location.$connectivity.data.median.$view.breakdown.image.bytes"
    }
   ]
  }
 ]
}