{
 "title": "WebPageTest leaderboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "${VAR_NAMESPACE}" },
   { "name": "path", "label": "path", "query": "$namespace.*" },
   { "name": "domains", "label": "domains", "query": "$namespace.$path.pageSummary.*" },
   {
    "name": "pages",
    "label": "pages",
    "query": "$namespace.$path.pageSummary.$domains.*"
   },
   {
    "name": "location",
    "label": "location",
    "query": "$namespace.$path.pageSummary.$domains.$pages.webpagetest.*"
   },
   {
    "name": "connectivity",
    "label": "connectivity",
    "query": "$namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.*"
   },
   {
    "name": "view",
    "label": "view",
    "query": "$namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.*"
   }
  ]
 },
 "panels": [
  { "title": "Visual Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "First Visual Change",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.render,'average'), 3, 4)"
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex,'average'), 3, 4)"
    }
   ]
  },
  {
   "title": "Visual Metrics history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Visual Change",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.render, 3, 4)"
      }
     ]
    },
    {
     "title": "Speed Index",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.SpeedIndex, 3, 4)"
      }
     ]
    },
    {
     "title": "Visual Complete 85%",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.visualComplete85, 3, 4)"
      }
     ]
    },
    {
     "title": "Last Visual Change",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.lastVisualChange, 3, 4)"
      }
     ]
    }
   ]
  },
  { "title": "Interactive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Time to interactive",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.TimeToInteractive,'average'), 3, 4)"
    }
   ]
  },
  {
   "title": "Last Interactive",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.LastInteractive,'average'), 3, 4)"
    }
   ]
  },
  { "title": "JavaScript", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "JavaScript Size",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.breakdown.js.bytes,'average'), 3, 4)"
    }
   ]
  },
  {
   "title": "JavaScript Requests",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "target": "aliasByNode(sortBy($namespace.$path.pageSummary.$domains.$pages.webpagetest.$location.$connectivity.data.median.$view.breakdown.js.requests,'average'), 3, 4)"
    }
   ]
  }
 ]
}